/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/T1hrwa4wCMq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function Component() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-6 px-4 md:px-6">
        <div className="container max-w-6xl mx-auto flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">Stock View</span>
          </Link>
          <div className="relative flex-1 ml-4 md:ml-8 lg:ml-12">
            <div className="absolute left-2.5 top-2.5 h-4 w-4 text-primary-foreground" />
            <Input
              type="search"
              placeholder="Search for stocks"
              className="w-full rounded-lg bg-primary-foreground/20 pl-8 pr-4 py-2 text-primary-foreground focus:outline-none focus:ring-2 focus:ring-primary-foreground focus:ring-opacity-50" />
          </div>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Screen View
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              News
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Trending
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              About
            </Link>
          </nav>
          <Button variant="outline" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-primary py-12 md:py-24 lg:py-32">
          <div className="container max-w-6xl mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h1 className="text-3xl md:text-5xl font-bold text-primary-foreground mb-4">
                  Unlock the power of stock screening
                </h1>
                <p className="text-primary-foreground/80 text-lg md:text-xl mb-6">
                  Discover the best stocks for your portfolio with our advanced screening tools.
                </p>
              </div>
              <div className="hidden md:block">
                <img
                  src="/placeholder.svg"
                  width={500}
                  height={400}
                  alt="Hero"
                  className="rounded-lg"
                  style={{ aspectRatio: "500/400", objectFit: "cover" }} />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container max-w-6xl mx-auto px-4 md:px-6">
            <div className="mb-8">
              <h2 className="text-3xl md:text-4xl font-bold mb-2">Featured Stock Screens</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Explore our curated collection of stock screens.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Value Stocks</div>
                  <h3 className="text-xl font-bold">Find Undervalued Gems</h3>
                  <p className="text-muted-foreground">Uncover stocks trading below their intrinsic value.</p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Try Now
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Growth Stocks</div>
                  <h3 className="text-xl font-bold">Find High-Growth Potential</h3>
                  <p className="text-muted-foreground">Identify stocks with strong growth prospects.</p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Try Now
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Dividend Stocks</div>
                  <h3 className="text-xl font-bold">Find High-Yielding Dividends</h3>
                  <p className="text-muted-foreground">Discover stocks with sustainable and growing dividends.</p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Try Now
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24 lg:py-32">
          <div className="container max-w-6xl mx-auto px-4 md:px-6">
            <div className="mb-8">
              <h2 className="text-3xl md:text-4xl font-bold mb-2">Latest News</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Stay up-to-date with the latest market news and insights.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={225}
                    alt="News"
                    className="rounded-lg w-full aspect-video object-cover" />
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Market News</div>
                  <h3 className="text-xl font-bold">Federal Reserve Raises Interest Rates</h3>
                  <p className="text-muted-foreground">
                    The Federal Reserve has announced another interest rate hike to combat inflation.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Read More
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={225}
                    alt="News"
                    className="rounded-lg w-full aspect-video object-cover" />
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Industry Insights</div>
                  <h3 className="text-xl font-bold">The Future of Electric Vehicles</h3>
                  <p className="text-muted-foreground">
                    Exploring the latest trends and innovations in the EV industry.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Read More
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={225}
                    alt="News"
                    className="rounded-lg w-full aspect-video object-cover" />
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Market Analysis</div>
                  <h3 className="text-xl font-bold">Top Performing Sectors in Q2</h3>
                  <p className="text-muted-foreground">
                    A deep dive into the best-performing sectors in the second quarter.
                  </p>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Read More
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container max-w-6xl mx-auto px-4 md:px-6">
            <div className="mb-8">
              <h2 className="text-3xl md:text-4xl font-bold mb-2">Trending Stocks</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Check out the stocks that are making waves in the market.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Technology</div>
                  <h3 className="text-xl font-bold">Apple Inc. (AAPL)</h3>
                  <p className="text-muted-foreground">The tech giant continues to dominate the smartphone market.</p>
                  <div className="flex items-center gap-2">
                    <div className="text-lg font-bold">$150.25</div>
                    <div className="text-sm text-green-500 font-medium">+2.5%</div>
                  </div>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Analyze
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Energy</div>
                  <h3 className="text-xl font-bold">Exxon Mobil Corp. (XOM)</h3>
                  <p className="text-muted-foreground">
                    The oil and gas giant is benefiting from rising energy prices.
                  </p>
                  <div className="flex items-center gap-2">
                    <div className="text-lg font-bold">$95.75</div>
                    <div className="text-sm text-green-500 font-medium">+3.2%</div>
                  </div>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Analyze
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col items-start gap-4">
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Healthcare</div>
                  <h3 className="text-xl font-bold">Johnson & Johnson (JNJ)</h3>
                  <p className="text-muted-foreground">The pharmaceutical giant continues to deliver strong results.</p>
                  <div className="flex items-center gap-2">
                    <div className="text-lg font-bold">$175.50</div>
                    <div className="text-sm text-green-500 font-medium">+1.8%</div>
                  </div>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}>
                    Analyze
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
