/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/T1hrwa4wCMq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import Header from "./Header";
import HomeSection from "./HomeSection";
import NewsFeed from "./NewsFeed";
import { TrendingStocks } from "./TrendingStocks";
import FeaturedStocks from "./FeaturedStocks";
import RealTimeChart from "./RealTimeChart";// Adjust the path based on your file structure
import TradingViewWidget from "./RealTimeChart";

export function Initial_comp() {
  
  return (
    (<div className="flex flex-col min-h-[100dvh]">

      <Header/>
      <main className="flex-1">
        <HomeSection/>
        {/* <TradingViewWidget/> */}
        <FeaturedStocks/>
        <NewsFeed/>
        <TrendingStocks/>
      </main>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
